INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Louvauve','qwgknosdf', TO_DATE('2022-11-13', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Louvauve','qNWERVB', TO_DATE('2022-12-13', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Sunadut','etyjeyil', TO_DATE('2022-11-30', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Sunadut','qetysrj', TO_DATE('2022-12-30', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Cicagna','riwerg', TO_DATE('2022-11-10', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Cicagna','iykrgqw', TO_DATE('2022-11-17', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Tuy Hòa','jylkftfq', TO_DATE('2022-11-05', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Tuy Hòa','etyj', TO_DATE('2022-11-12', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Tuy Hòa','jqwerewr', TO_DATE('2022-11-19', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Tuy Hòa','iersdfaw', TO_DATE('2022-11-26', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Oslo','yrqres', TO_DATE('2022-11-02', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Oslo','qejtfn', TO_DATE('2022-11-09', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Oslo','ryjdhn', TO_DATE('2022-11-16', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Wyoming','qtrjsr', TO_DATE('2022-12-01', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Wyoming','qdfb b', TO_DATE('2022-12-08', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Borongan','qerghnagdb', TO_DATE('2022-12-08', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Borongan','qergqwe', TO_DATE('2022-12-15', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Bajgecy','wmwegw', TO_DATE('2022-12-11', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Bajgecy','whasdf', TO_DATE('2022-12-18', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Quity','adfnawefb', TO_DATE('2022-12-28', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Quity',',yhetwaw', TO_DATE('2022-12-30', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Eastdon','qersub', TO_DATE('2022-11-07', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Eastdon','yhsqwrr', TO_DATE('2022-11-14', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Tampico','afdgen-us', TO_DATE('2023-01-01', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Tampico','aw4rgmbf', TO_DATE('2023-01-08', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Sfruz','Mrtwjgsd', TO_DATE('2023-01-22', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Sfruz','Methnfgb', TO_DATE('2023-01-29', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Sanrt','qwweerr', TO_DATE('2023-02-25', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Sanrt','qwqwnrer', TO_DATE('2023-03-01', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Galway','gwrqrs', TO_DATE('2022-11-22', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Galway','fgheergus', TO_DATE('2022-11-22', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Sengkang','sdvsdfs', TO_DATE('2022-11-15', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Sengkang','qwerhns', TO_DATE('2022-11-22', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Hatla','Hhngbsdz', TO_DATE('2022-12-09', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Hatla','Hf,hgter', TO_DATE('2022-12-16', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Yunnan','qwecvbn', TO_DATE('2022-12-16', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Yunnan','qqwy', TO_DATE('2022-12-29', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Flin Flon','xvbcvn/fr', TO_DATE('2022-11-04', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Flin Flon','xdfgfq', TO_DATE('2022-11-11', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Lehrte','Drtyea', TO_DATE('2022-11-28', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Lehrte','msgergw', TO_DATE('2022-12-04', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Bayreuth','vcsadfngs', TO_DATE('2022-11-24', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Bayreuth','vwrtjdfgb', TO_DATE('2022-11-30', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Alcorcón','zbzfwne', TO_DATE('2022-12-31', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Alcorcón','sfgmbds', TO_DATE('2023-01-07', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Dutse','qwrbwfqgs', TO_DATE('2023-03-11', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Dutse','qwjwrs', TO_DATE('2023-03-18', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Dutse','qmtnfg', TO_DATE('2023-03-25', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Dutse','qw5ka', TO_DATE('2023-04-01', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Melbourne','sfhdgasf', TO_DATE('2023-11-28', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Melbourne','sth,qrt', TO_DATE('2023-12-05', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Melbourne','sfasf', TO_DATE('2023-12-12', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Paraíso','zvnser', TO_DATE('2023-02-02', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Paraíso','zrtngnd', TO_DATE('2023-02-09', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Paraíso','wernsdf', TO_DATE('2023-02-16', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Paraíso','zerzvr', TO_DATE('2023-02-23', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Paraíso','zqwercbr', TO_DATE('2023-03-01', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Olsztyn','mgnvfds', TO_DATE('2022-11-27', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Olsztyn','qwegbsd', TO_DATE('2022-11-28', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Matamoros','qwefzxcv', TO_DATE('2023-12-01', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Matamoros','qwrtjwq', TO_DATE('2023-12-01', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Uitkerke','qwwadfdsf', TO_DATE('2022-11-15', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Uitkerke','dfnfwq', TO_DATE('2022-11-19', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Vienna','asdegf', TO_DATE('2022-11-17', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Vienna','asdg12', TO_DATE('2022-11-25', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Pocheon','576tsd', TO_DATE('2022-11-19', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Pocheon','5wrgafsd', TO_DATE('2022-11-26', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Valuyki','wgwwer', TO_DATE('2022-11-20', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Valuyki','wgnaee', TO_DATE('2022-11-27', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Calama','rhqen', TO_DATE('2022-11-23', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Calama','rqwernn', TO_DATE('2022-11-30', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Nizip','xndtyenu', TO_DATE('2022-11-25', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Nizip','xqwerndsf', TO_DATE('2022-11-25', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Heule','q3trbw', TO_DATE('2022-12-04', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Heule','q34qwev', TO_DATE('2022-12-11', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Heule','q3vnvs', TO_DATE('2022-12-18', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Ivankivsk','q3rnwetj', TO_DATE('2022-12-10', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Ivankivsk','q3wnf', TO_DATE('2022-12-17', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Slshalsen','wtasd', TO_DATE('2023-12-05', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Slshalsen','wtnee', TO_DATE('2023-12-12', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Slshalsen','wt1bs', TO_DATE('2023-12-19', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Slshalsen','qrnsdf', TO_DATE('2023-12-16', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Khybeency','qsxmasdhrt', TO_DATE('2023-02-14', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Khybeency','qsxmatnew', TO_DATE('2023-02-21', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Khybeency','qsqwerrt', TO_DATE('2023-02-27', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Khybeency','hdhrt', TO_DATE('2023-03-03', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Khybeency','qfsft', TO_DATE('2023-03-10', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Wieneadt','snfqwersbg', TO_DATE('2023-01-04', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Wieneadt','sesbg', TO_DATE('2023-01-11', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('De Klinge','exmafqwrt', TO_DATE('2023-02-14', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('De Klinge','eweafrt', TO_DATE('2023-02-21', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Okene','qermvsdaf', TO_DATE('2022-12-18', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Okene','gweaf', TO_DATE('2022-12-25', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Bogotá','xashadfnm', TO_DATE('2022-12-23', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Bogotá','xaktwe', TO_DATE('2022-12-30', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Astore','rtmxcwr', TO_DATE('2022-11-11', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Astore','rertq', TO_DATE('2022-11-18', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Astore','bdfvgwer', TO_DATE('2022-11-25', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Astore','ngtcret', TO_DATE('2022-12-09', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Melbray','werhncns', TO_DATE('2022-11-13', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Melbray','wrgwf', TO_DATE('2022-11-20', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Melbray','rtrgqqm', TO_DATE('2022-11-27', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Koronadal','dqerhdfb', TO_DATE('2022-11-14', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Koronadal','dqqweb', TO_DATE('2022-11-21', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Bremen','adfbsdrf', TO_DATE('2022-11-15', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Bremen','nweqbq', TO_DATE('2022-11-22', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Kosnivka','adfgsaefr', TO_DATE('2022-11-17', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Kosnivka','snweqr', TO_DATE('2022-11-25', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Lelystad','asdfvbfg', TO_DATE('2022-12-16', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Lelystad','newfewe', TO_DATE('2022-12-23', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Kursk','Radfnsd0', TO_DATE('2022-11-30', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Kursk','qwend0', TO_DATE('2022-12-01', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Kursk','Radmgfs0', TO_DATE('2022-12-08', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Kursk','mytrd0', TO_DATE('2022-12-15', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Boca o','Hqrtgfbte', TO_DATE('2022-12-15', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Boca o','Hqrne', TO_DATE('2022-12-22', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Monoro','Cfqwfdbo', TO_DATE('2022-12-20', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Monoro','mfrbo', TO_DATE('2022-12-25', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Bregenz','asdfaf', TO_DATE('2023-10-11', 'YYYY-MM-DD'));
INSERT INTO Events (SurfSite_ID,Announcment_No,DurationDate)
VALUES ('Bregenz','kontdf', TO_DATE('2023-10-19', 'YYYY-MM-DD'));